# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: chain_social_indexer
networks:
- id: 1998991
  start_block: 0
  contracts:
  - name: ChainSocial
    address:
    - 0x17E81bE1e4FD51332C6B09e16B4AB83Bf5a633D2
    handler: ./src/EventHandlers.js
    events:
    - event: CommentAdded(uint256 indexed commentId, uint256 indexed postId, address indexed author, string content)
    - event: Followed(address indexed follower, address indexed followed)
    - event: PostCreated(uint256 indexed postId, address indexed author, string content)
    - event: PostLiked(uint256 indexed postId, address indexed liker)
    - event: Unfollowed(address indexed follower, address indexed followed)
    - event: UserCreated(address indexed userAddress, string username)
